name: Build (nix)

on:
  push:
    branches:
    - master
    - ci-*
    - release*
    paths: &trigger_path_list
    - '.github/workflows/nix.yml'
    - 'Agda.cabal'
    - 'Setup.hs'
    - '**.nix'
    - 'flake.lock'
    - 'src/agda-mode/**'
    - 'src/full/**'
    - 'src/main/**'
    - 'src/size-solver/**'
    - 'test/**.hs'
  pull_request:
    paths: *trigger_path_list

jobs:

  nix:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v17

    - name: Nix develop
      run: nix develop --ignore-environment --command fix-whitespace --check

    - name: Nix build
      run: nix build --verbose .#AgdaNonOptimized --print-build-logs

    - name: Nix shell
      run: nix shell --verbose .#AgdaNonOptimized --command agda --version
